configured_endpoints: 5
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/benchify%2Fbenchify-ee31083c5de426f6fab7796da281b29fcf814ddfbb4cfca185d55c7ac09d5501.yml
openapi_spec_hash: 6efc1555e11f3e3709daba7ebda7f287
config_hash: a0ad25d56ec0fdf45c42961ebf169dd2
