
export const BALANCE_CONSTANTS = {
    PLAYER_SPEED: 200,
    PLAYER_JUMP_VELOCITY: 450,
    GRAVITY: 800,
    WORLD_WIDTH_IN_BLOCKS: 200,
    WORLD_HEIGHT_IN_BLOCKS: 100,
    MINING_BASE_DURATION_MS: 300,
    MAX_REACH_IN_BLOCKS: 5,
};
